[ FIX ] Add onSuccessfulLogin callback to genericAuthPlugin
FrostDigital/flink-framework pull request #32
Opened 2024-11-07 17:03 UTC by nilsok

Adds `onSuccessfulLogin` callback in `generic-auth-plugin`

2024-11-07 17:04 UTC, nilsok commented
Should i commit new `package.json`s as well? 🤔

2024-11-08 08:41 UTC, joelso reviewed
LGTM 👍

2024-11-08 08:43 UTC, joelso requested changes

2024-11-08 08:43 UTC, joelso commented on packages/generic-auth-plugin/src/coreFunctions.ts
> +        if (onSuccessfulLogin != null) {
Oops saw this just after posted review. Shouldn't this be a falsy check, not just null?

2024-11-08 08:50 UTC, nilsok commented on packages/generic-auth-plugin/src/coreFunctions.ts
> +        if (onSuccessfulLogin != null) {
Good catch! 🙂 - I used the null-check because i saw that it was used here, and thought that there is probably some reason for this 😅: https://github.com/FrostDigital/flink-framework/blob/fix/add-on-successful-login-callback/packages/generic-auth-plugin/src/coreFunctions.ts#L73 - but maybe it should be a falsy check there also?

2024-11-08 09:02 UTC, joelso approved these changes

2024-11-08 09:02 UTC, merged